[env]
_.file = ".env"
DATABASE_URL = "postgres://postgres:postgres@localhost:5432/spandrel"

[tools]
python = "3.10"
rust = "latest"
github-cli = "latest"
postgres = "17"

[tasks]
setup = "bash setup.sh"
reset-db = "bash reset_db.sh"
worker = "python worker.py"
