[env]
_.file = ".env"
DATABASE_URL = "postgres://postgres:postgres@localhost:5432/spandrel"

[tools]
python = "3.12"
ruff = "latest"
rust = "latest"
github-cli = "latest"
postgres = "17"

[tasks.lint]
description = "Lint and format"
run = """
ruff check --fix .
ruff format .
"""